# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-24 06:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trx_id', models.CharField(max_length=9)),
                ('address_ship', models.CharField(max_length=255)),
                ('date_order', models.DateTimeField()),
                ('seller_name', models.CharField(max_length=255)),
                ('delivery_service', models.CharField(max_length=10)),
            ],
        ),
    ]
